.TH REMBG 1 "Januar 2026" "2.0.72" "User Commands"
.SH NAME
rembg \- tool to remove background from images
.SH SYNOPSIS
.B rembg
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.B rembg
is a tool to remove images background.
.PP
It works as a command line interface and a library.
.SH OPTIONS
.TP
.BR \-\-version
Show the version and exit.
.TP
.BR \-\-help
Show this message and exit.
.SH SEE ALSO
Full documentation at: <https://github.com/danielgatis/rembg>
